services:

  web:
    container_name: web_app_container
    image: drorganvidez/boilerplate:dev
    env_file:
      - ../.env
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "bash", "-c", "bash /app/docker/entrypoints/development_entrypoint.sh" ]
    networks:
      - boilerplate_network

  db:
    container_name: mariadb_container
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - boilerplate_network

  nginx:
    container_name: nginx_web_server_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - boilerplate_network

  redis:
    image: "redis:latest"
    container_name: redis_container
    restart: always
    networks:
      - boilerplate_network

  worker:
    container_name: rq_worker_container
    env_file:
      - ../.env
    depends_on:
      - redis
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.worker
    volumes:
      - ../app/:/app/app
      - ../core/:/app/core
      - ../uploads/:/app/uploads
    networks:
      - boilerplate_network

volumes:
  db_data:

networks:
  boilerplate_network:
    driver: bridge
    name: boilerplate_network
