version: "3.9"

services:
  web:
    container_name: web_app_container
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.dev
    image: diplomas_web_app:latest
    env_file:
      - ../.env
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["bash", "-c", "bash /app/docker/entrypoints/development_entrypoint.sh"]
    networks:
      - my_network

  db:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: diplomasdb_root_password
      MARIADB_DATABASE: diplomasdb
      MARIADB_USER: diplomasdb_user
      MARIADB_PASSWORD: diplomasdb_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    external: true
    name: innosoft-diplomas-1_my_network
