"""changes diploma_template

Revision ID: 081d7743aa9c
Revises: 37d34d8d57d3
Create Date: 2024-11-26 12:54:08.443121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081d7743aa9c'
down_revision = '37d34d8d57d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma_templates', schema=None) as batch_op:
        batch_op.alter_column('custom_text',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma_templates', schema=None) as batch_op:
        batch_op.alter_column('custom_text',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
