"""empty message

Revision ID: 186163182c62
Revises: 
Create Date: 2024-11-13 12:12:43.949338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '186163182c62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diploma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('uvus', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('perfil', sa.String(length=120), nullable=False),
    sa.Column('participacion', sa.String(length=20), nullable=False),
    sa.Column('comite', sa.String(length=255), nullable=True),
    sa.Column('evidencia_aleatoria', sa.Float(), nullable=True),
    sa.Column('horas_de_evidencia_aleatoria', sa.Float(), nullable=True),
    sa.Column('eventos_asistidos', sa.Integer(), nullable=True),
    sa.Column('horas_de_asistencia', sa.Float(), nullable=True),
    sa.Column('reuniones_asistidas', sa.Integer(), nullable=True),
    sa.Column('horas_de_reuniones', sa.Float(), nullable=True),
    sa.Column('bono_de_horas', sa.Float(), nullable=True),
    sa.Column('evidencias_registradas', sa.Integer(), nullable=True),
    sa.Column('horas_de_evidencias', sa.Float(), nullable=True),
    sa.Column('horas_en_total', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('perfil'),
    sa.UniqueConstraint('uvus')
    )
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token_expire')
        batch_op.drop_index('ix_user_token_token')
        batch_op.drop_index('token')

    op.drop_table('user_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_index('username')
        batch_op.drop_column('change_email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('username')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('user_profile_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('bio')
        batch_op.drop_column('avator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avator', mysql.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('bio', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_profile_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=25), nullable=False))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=25), nullable=False))
        batch_op.add_column(sa.Column('change_email', mysql.VARCHAR(length=120), nullable=True))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=120),
               nullable=False)

    op.create_table('user_token',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=72), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('expire', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_token_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.create_index('token', ['token'], unique=True)
        batch_op.create_index('ix_user_token_token', ['token'], unique=False)
        batch_op.create_index('ix_user_token_expire', ['expire'], unique=False)

    op.drop_table('diploma')
    # ### end Alembic commands ###
