"""Initial migration with diploma

Revision ID: 54fe68134e69
Revises: 
Create Date: 2024-11-01 13:47:00.534358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54fe68134e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diploma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('uvus', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('perfil', sa.String(length=120), nullable=False),
    sa.Column('participacion', sa.String(length=20), nullable=False),
    sa.Column('comite', sa.String(length=255), nullable=True),
    sa.Column('evidencia_aleatoria', sa.Float(), nullable=True),
    sa.Column('horas_de_evidencia_aleatoria', sa.Float(), nullable=True),
    sa.Column('eventos_asistidos', sa.Integer(), nullable=True),
    sa.Column('horas_de_asistencia', sa.Float(), nullable=True),
    sa.Column('reuniones_asistidas', sa.Integer(), nullable=True),
    sa.Column('horas_de_reuniones', sa.Float(), nullable=True),
    sa.Column('bono_de_horas', sa.Float(), nullable=True),
    sa.Column('evidencias_registradas', sa.Integer(), nullable=True),
    sa.Column('horas_de_evidencias', sa.Float(), nullable=True),
    sa.Column('horas_en_total', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('perfil'),
    sa.UniqueConstraint('uvus')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('change_email', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_profile',
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('avator', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.String(length=38), nullable=False),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_token',
    sa.Column('token', sa.String(length=72), nullable=False),
    sa.Column('salt', sa.String(length=20), nullable=False),
    sa.Column('expire', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=38), nullable=False),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.create_index('ix_user_token_expire', ['expire'], unique=False)
        batch_op.create_index('ix_user_token_token', ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token_token')
        batch_op.drop_index('ix_user_token_expire')

    op.drop_table('user_token')
    op.drop_table('user_profile')
    op.drop_table('user')
    op.drop_table('diploma')
    # ### end Alembic commands ###
