"""Added sent atribute to diploma table

Revision ID: 5909a1b3e738
Revises: b81958f7815e
Create Date: 2024-11-11 12:06:57.504598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5909a1b3e738'
down_revision = 'b81958f7815e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma', schema=None) as batch_op:
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
