"""Add Diploma table

Revision ID: b81958f7815e
Revises: 001
Create Date: 2024-11-08 12:23:49.339754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81958f7815e'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diploma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('uvus', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('perfil', sa.String(length=120), nullable=False),
    sa.Column('participacion', sa.String(length=20), nullable=False),
    sa.Column('comite', sa.String(length=255), nullable=True),
    sa.Column('evidencia_aleatoria', sa.Float(), nullable=True),
    sa.Column('horas_de_evidencia_aleatoria', sa.Float(), nullable=True),
    sa.Column('eventos_asistidos', sa.Integer(), nullable=True),
    sa.Column('horas_de_asistencia', sa.Float(), nullable=True),
    sa.Column('reuniones_asistidas', sa.Integer(), nullable=True),
    sa.Column('horas_de_reuniones', sa.Float(), nullable=True),
    sa.Column('bono_de_horas', sa.Float(), nullable=True),
    sa.Column('evidencias_registradas', sa.Integer(), nullable=True),
    sa.Column('horas_de_evidencias', sa.Float(), nullable=True),
    sa.Column('horas_en_total', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('perfil'),
    sa.UniqueConstraint('uvus')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diploma')
    # ### end Alembic commands ###
