"""Add sent field to Diploma model

Revision ID: db6ae3528180
Revises: 54fe68134e69
Create Date: 2024-11-10 19:28:35.314094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6ae3528180'
down_revision = '54fe68134e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diploma', schema=None) as batch_op:
        batch_op.drop_column('sent')

    # ### end Alembic commands ###
