"""initial_migration

Revision ID: fb4585877663
Revises: 
Create Date: 2024-10-10 12:12:50.993619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4585877663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('change_email', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_profile',
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('avator', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.String(length=38), nullable=False),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_token',
    sa.Column('token', sa.String(length=72), nullable=False),
    sa.Column('salt', sa.String(length=20), nullable=False),
    sa.Column('expire', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=38), nullable=False),
    sa.Column('id', sa.String(length=38), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.create_index('ix_user_token_expire', ['expire'], unique=False)
        batch_op.create_index('ix_user_token_token', ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token_token')
        batch_op.drop_index('ix_user_token_expire')

    op.drop_table('user_token')
    op.drop_table('user_profile')
    op.drop_table('user')
    # ### end Alembic commands ###
