name: Commits Syntax Checker

on:
  pull_request:
    branches: [main, preproduction]
    types: [opened, reopened, edited, synchronize]
  push:
    branches:
      - "main"
      - "preproduction"

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Commitlint
        run: npm install -g @commitlint/{cli,config-conventional}

      - name: Create Custom Commitlint Config
        run: |
          echo "module.exports = { extends: ['@commitlint/config-conventional'], rules: { 'header-pattern': [2, 'always', /^\\[\\w+\\]\\s.+/] } };" > commitlint.config.js

      - name: Validate Commit Messages
        run: |
          RANGE=$(git log --format=%s ${{ github.event.before }}..${{ github.sha }} || echo "HEAD")
          echo "$RANGE" | commitlint