name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
      - preproduction
  pull_request:
    branches:
      - main
      - preproduction

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:

      - name: Install Snyk CLI
        if: env.skip == 'false'
        run: npm install -g snyk

      - name: Authenticate with Snyk
        if: env.skip == 'false'
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        if: env.skip == 'false'
        run: snyk test

      - name: Mark job as success if skipped
        if: env.skip == 'true'
        run: echo "Snyk scan skipped due to lack of secrets."