name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
      - preproduction
  pull_request:
    branches:
      - main
      - preproduction

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Comprobar si los secretos están disponibles
      - name: Check for secrets availability
        id: secrets-check
        run: |
          if [ -z "$SNYK_TOKEN" ]; then
            echo "Secrets are not available, skipping Snyk scan."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Secrets are available, proceeding with Snyk scan."
            echo "skip=false" >> $GITHUB_ENV
          fi

      # Paso 2: Instalar Snyk CLI si los secretos están disponibles
      - name: Install Snyk CLI
        if: env.skip == 'false'
        run: npm install -g snyk

      # Paso 3: Autenticarse con Snyk
      - name: Authenticate with Snyk
        if: env.skip == 'false'
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Paso 4: Ejecutar el análisis Snyk
      - name: Run Snyk Test
        if: env.skip == 'false'
        run: snyk test

      # Paso 5: Marcar como éxito si se omitió
      - name: Mark job as success if skipped
        if: env.skip == 'true'
        run: echo "Snyk scan skipped due to lack of secrets."
