name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
      - preproduction
  pull_request:
    branches:
      - main
      - preproduction

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for secrets availability
        id: secrets-check
        run: |
          if [ -z "${{ secrets.SNYK_TOKEN }}" ]; then
            echo "Secrets are not available, skipping Snyk scan."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Secrets are available, proceeding with Snyk scan."
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Install Snyk CLI
        if: env.skip == 'false'
        run: npm install -g snyk

      - name: Install dependencies (Node.js)
        if: env.skip == 'false'
        run: npm install

      - name: Run Snyk Test
        if: env.skip == 'false'
        run: snyk test --file=requirements.txt || echo "No supported files found. Skipping Snyk test."
