name: Security Tests

on:
  push:
    branches:
      - main
      - preproduction
  pull_request:
    branches:
      - main
      - preproduction

jobs:
  snyk-security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (si tu proyecto es Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test (Vulnerabilities in dependencies)
        run: snyk test

      - name: Run Snyk monitor (Monitor for vulnerabilities over time)
        run: snyk monitor

  notify-security-results:
    if: failure()
    runs-on: ubuntu-latest
    needs: snyk-security-scan

    steps:
      - name: Send security failure notification to Slack
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: 'your-channel-id'  # Reemplaza con tu Channel ID
          slack-message: |
            :warning: *Security Alert: Vulnerabilities Found* 
            Commit URL: ${{ github.event.head_commit.url }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Committer: ${{ github.actor }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
