name: Run tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: boilerplate_root_password
          MYSQL_DATABASE: boilerplatedb_test
          MYSQL_USER: boilerplate_user
          MYSQL_PASSWORD: boilerplate_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    # Configuración para verificar la compatibilidad con versiones de Python 3.10, 3.11 y 3.12
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Verificar si hay dependencias desactualizadas
    - name: Check for outdated dependencies
      run: |
        pip list --outdated

    # Instalar las dependencias del proyecto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Análisis de seguridad con pip-audit
    - name: Security audit with pip-audit
      run: |
        pip install pip-audit
        pip-audit || true

    # Preparar el entorno (eliminar dependencias locales si es necesario)
    - name: Prepare environment
      run: |
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    # Ejecutar las pruebas
    - name: Run Tests
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: boilerplatedb_test
        MARIADB_USER: boilerplate_user
        MARIADB_PASSWORD: boilerplate_password
      run: |
        pytest app/modules/ --ignore-glob='*selenium*'
